/**
 * CNB 代码托管 Agent 工具 —— 10 个 cnb_* 工具。
 * 安全边界：令牌绝不回显；推送默认关闭；克隆地址支持 owner/repo slug。
 */
import { defineTool } from '@deepseek-ai/dsh-tools'
import type { CnbEngine } from './engine.ts'
type ContentBlock = { type: 'text'; text: string }
function text(value: string): ContentBlock[] { return [{ type: 'text', text: value }] }
function render(value: unknown): string { return JSON.stringify(value, null, 2) }
function jsonValue(value: unknown): any { return JSON.parse(JSON.stringify(value)) }
const schema = { type: 'json' } as const

export function cnbAuthAddTool(engine: CnbEngine) { return defineTool({ name: 'cnb_auth_add', description: '添加或更新 CNB（cnb.cool）账号：保存访问令牌到本机 0600 文件，绝不回显。令牌在 cnb.cool 个人设置 → 访问令牌 创建；首次添加后建议调用 cnb_auth_test 验证。', parameters: { alias: { type: 'string', required: true, description: '账号别名（本地标识，可任意，如 cnb-main）。' }, token: { type: 'string', required: true, description: 'CNB 访问令牌。' } }, output: { schema, render: (_args, value) => text(render(value)) }, async execute(args) { return jsonValue({ account: engine.store.upsertAccount({ alias: args.alias, token: args.token }) }) } }) }
export function cnbAuthRemoveTool(engine: CnbEngine) { return defineTool({ name: 'cnb_auth_remove', description: '删除一个已配置的 CNB 账号（本机令牌记录），不影响 cnb.cool 上的令牌本身。', parameters: { alias: { type: 'string', required: true, description: '要删除的账号别名。' } }, output: { schema, render: (_args, value) => text(render(value)) }, async execute(args) { engine.store.deleteAccount(args.alias); return jsonValue({ ok: true }) } }) }
export function cnbAuthListTool(engine: CnbEngine) { return defineTool({ name: 'cnb_auth_list', description: '列出已配置的 CNB 账号（不回显令牌）。在 CNB 仓库或 Git 操作前别名未知时先用它。', parameters: {}, output: { schema, render: (_args, value) => text(render(value)) }, async execute() { return jsonValue({ accounts: engine.listAccounts() }) } }) }
export function cnbAuthTestTool(engine: CnbEngine) { return defineTool({ name: 'cnb_auth_test', description: '验证已配置的 CNB 账号令牌并返回认证用户名；从不返回令牌。', parameters: { account: { type: 'string', description: '账号别名；已配置默认账号时可省略。' } }, output: { schema, render: (_args, value) => text(render(value)) }, async execute(args) { return jsonValue(await engine.testAccount(args.account)) } }) }
export function cnbRepoListTool(engine: CnbEngine) { return defineTool({ name: 'cnb_repo_list', description: '列出当前 CNB 账号可见的我的仓库，可按名称/描述过滤；返回仓库元数据与克隆地址。', parameters: { account: { type: 'string', description: '账号别名。' }, query: { type: 'string', description: '按名称或描述过滤。' } }, output: { schema, render: (_args, value) => text(render(value)) }, async execute(args) { return jsonValue({ repos: await engine.listRepos(args.account, args.query) }) } }) }
export function cnbCloneTool(engine: CnbEngine) { return defineTool({ name: 'cnb_clone', description: '克隆 CNB 仓库到本机绝对路径目录。remoteUrl 支持 owner/repo、cnb.cool/… 或完整 https URL；令牌经临时 HTTP 头注入，绝不写入 URL。公开仓库可匿名克隆。', parameters: { remoteUrl: { type: 'string', required: true, description: 'owner/repo 或完整仓库地址。' }, destination: { type: 'string', required: true, description: '本机绝对目标目录（必须不存在）。' }, account: { type: 'string', description: '账号别名；省略且无已配置账号时匿名克隆（仅公开仓库）。' }, branch: { type: 'string', description: '可选分支。' }, timeoutMs: { type: 'integer', description: '超时（毫秒）。' } }, output: { schema, render: (_args, value) => text(render(value)) }, async execute(args) { return jsonValue(await engine.action({ action: 'clone', ...args })) } }) }
export function cnbPullTool(engine: CnbEngine) { return defineTool({ name: 'cnb_pull', description: '对一个本机 CNB Git 仓库执行快进拉取（--ff-only）。', parameters: { repoPath: { type: 'string', required: true, description: '本机 Git 仓库绝对路径。' }, account: { type: 'string', description: '账号别名；私有仓库拉取需要。' }, remote: { type: 'string', description: '远端名，默认 origin。' }, branch: { type: 'string', description: '可选分支。' }, timeoutMs: { type: 'integer', description: '超时（毫秒）。' } }, output: { schema, render: (_args, value) => text(render(value)) }, async execute(args) { return jsonValue(await engine.action({ action: 'pull', ...args })) } }) }
export function cnbPushTool(engine: CnbEngine) { return defineTool({ name: 'cnb_push', description: '推送本机 Git 仓库到 CNB。推送默认关闭，必须先在服务工厂设置的 CNB 配置里打开 Allow push；强制推送还需打开 Allow force push。', parameters: { repoPath: { type: 'string', required: true, description: '本机 Git 仓库绝对路径。' }, account: { type: 'string', description: '账号别名。' }, remote: { type: 'string', description: '远端名，默认 origin。' }, branch: { type: 'string', description: '可选分支。' }, force: { type: 'boolean', description: '使用 --force-with-lease；需要强制推送开关。' }, timeoutMs: { type: 'integer', description: '超时（毫秒）。' } }, output: { schema, render: (_args, value) => text(render(value)) }, async execute(args) { return jsonValue(await engine.action({ action: 'push', ...args })) } }) }
export function cnbStatusTool(engine: CnbEngine) { return defineTool({ name: 'cnb_status', description: '读取本机 Git 仓库状态（分支与变更文件），适用于 CNB 或任意本机仓库。', parameters: { repoPath: { type: 'string', required: true, description: '本机 Git 仓库绝对路径。' } }, output: { schema, render: (_args, value) => text(render(value)) }, async execute(args) { return jsonValue(await engine.action({ action: 'status', ...args })) } }) }
export function cnbCommitTool(engine: CnbEngine) { return defineTool({ name: 'cnb_commit', description: '创建一个本机 Git 提交（不推送）；推送请另行调用 cnb_push。', parameters: { repoPath: { type: 'string', required: true, description: '本机 Git 仓库绝对路径。' }, message: { type: 'string', required: true, description: '提交说明（项目规范要求中文）。' }, all: { type: 'boolean', description: '提交前暂存全部已跟踪与未跟踪变更。' }, timeoutMs: { type: 'integer', description: '超时（毫秒）。' } }, output: { schema, render: (_args, value) => text(render(value)) }, async execute(args) { return jsonValue(await engine.action({ action: 'commit', ...args })) } }) }
