/**
 * 250k 压缩用户预设的内置模板。
 *
 * 来源：本机验证过的 cordis-250k 预设（2026-09-10 暂存验收通过版本），
 * 做了两处精简以支持任意机器一键生成：
 * 1. 去掉 `tool-cordis` 自改工具集与预设内创作技能（skill-filesystem）——
 *    它们依赖按本机 DSH 版本现场生成的 compat 模块（内含绝对路径依赖，
 *    无法内置分发），需要完整创作模式时按文档手动生成；
 * 2. persona 改为标准编码代理身份，不再宣称可读写运行时。
 *
 * 保留部分与验证版逐字一致：shell/filesystem/jobs/goals/plan-mode/
 * delegation/workflows 全部标准编码能力，以及核心的 compaction 组
 * （thresholdRatio 0.25 + retainTokens 32768 + 工具结果裁剪器）。
 * 全部行引用 @deepseek-ai/dsh-* 官方包，版本跟随宿主，Windows/Mac 通用
 * （shell 行的平台差异由 `!!js process.platform` 表达式处理）。
 */

/** 预设标识（与 dsh-devforge 的 forgeAgentPreset 默认值一致）。 */
export const PRESET_ID = 'cordis-250k'

/** 压缩触发比例：模型窗口的 25%（1M 窗口即约 250k tokens）。 */
export const THRESHOLD_RATIO = 0.25

/** 压缩后保留的近期原文预算（tokens）。 */
export const RETAIN_TOKENS = 32768

/** 预设元数据（roster 展示用）。 */
export const PRESET_META_YAML = `name: 250k 压缩（天工造梦一键配置）
description: 标准编码能力 + 自动上下文压缩：模型窗口的 25% 触发压缩、保留 32k 近期原文（1M 窗口约 250k 触发）。由天工造梦一键配置生成；不含创作模式 cordis 工具集，需要时按 dsh-devforge 文档手动生成。
`

/** 预设组合文件（agent.cordis.yml）内容。 */
export const PRESET_COMPOSITION_YAML = `# The \`cordis-250k\` agent preset: the standard coding agent tuned for 250k
# context compaction, generated by dsh-devforge's one-click setup.
#
# It keeps every standard coding capability (shell, filesystem, jobs, goals,
# plan mode, delegation, workflows) and the tuned compaction group from the
# validated local preset. It intentionally omits the \`tool-cordis\`
# self-modification toolset and the preset-local composition-authoring skills:
# those require a per-machine generated compat module, documented in
# dsh-devforge docs/创造模式250k压缩预设.md.


# The preset's own persona, shadowing the deployment default for this agent.
# \`{{model}}\` and \`{{cwd}}\` resolve from the agent's own route and workspace.
- id: persona
  name: '@deepseek-ai/dsh-persona'
  config:
    suffix: Your working directory is {{cwd}}.
    prefix: |-
      You are a coding agent powered by the {{model}} model, running on the DeepSeek Harness. This session mounts the \`cordis-250k\` preset: standard coding capability with automatic context compaction tuned for large model windows.

- id: agent-instructions
  name: '@deepseek-ai/dsh-agent-instructions'
  config:
    maxBytes: 65536

# ── shell ───────────────────────────────────────────────────────────────────

# Both shell tools consume the host tool registry; the platform gate keeps the
# matching executor only, so the same file works on macOS/Linux and Windows.
- id: tool-bash
  name: '@deepseek-ai/dsh-tool-bash'
  disabled: !!js process.platform === 'win32'

- id: tool-pwsh
  name: '@deepseek-ai/dsh-tool-pwsh'
  disabled: !!js process.platform !== 'win32'

# ── filesystem ──────────────────────────────────────────────────────────────

# Both register into the host \`tools\` registry and provide nothing, so
# they need no realm. The \`fs\` service and its policy stay in the host.
- id: tool-fs
  name: '@deepseek-ai/dsh-tool-fs'

- id: tool-fs-search
  name: '@deepseek-ai/dsh-tool-fs-search'
  config:
    sampleOverCapGlobResults: false

# ── background jobs ────────────────────────────────────────────────────────

# Only the model-facing controls. The task REGISTRY stays on the host plane.
- id: tool-jobs
  name: '@deepseek-ai/dsh-tool-jobs'

# ── goals ───────────────────────────────────────────────────────────────────

# The goal service and session driver stay on the host plane; these are the
# human command and the model-facing tool in this preset's scoped layers.
- id: command-goal
  name: '@deepseek-ai/dsh-command-goal'

- id: tool-goal
  name: '@deepseek-ai/dsh-tool-goal'

# ── plan mode ───────────────────────────────────────────────────────────────

# Plan state is per-agent by nature, so an entry-local realm is not a
# workaround here — it is the correct lifetime.
- id: planning
  name: cordis:group
  group: true
  isolate:
    planMode: true
  config:
    - id: plan-mode
      name: '@deepseek-ai/dsh-plan-mode'
      config:
        section: |
              You are in plan mode. Stay in plan mode until exit_plan_mode succeeds or the user switches the session mode. Imperative language to implement changes means plan the implementation, not execute it. A user's conversational agreement — including an answer confirming something you asked — approves nothing and does not end plan mode; fold the confirmed decision into the plan and submit it through exit_plan_mode.

              Explore first. Use non-mutating reads, searches, static analysis, and checks to ground the plan in the actual repository. Do not edit or write files, change configuration, run formatters or code generation that rewrites tracked files, commit, or otherwise carry out the plan. Prefer existing functions and patterns over new machinery.

              The tool catalog stays the same across modes for request-cache stability. These plan-mode rules override any later tool description or guidance that suggests using mutation tools; those tools remain listed to keep the tool catalog unchanged. Do not use todo_write to track this planning phase: it tracks implementation after an approved plan, while the plan itself belongs in exit_plan_mode.

              Resolve discoverable facts by inspection. Use ask_user_question only for user-owned choices or material ambiguity that inspection cannot answer. Do not ask the user where code lives or how current behavior works when you can find out.

              Make the plan decision-complete: state the goal and success criteria; group implementation changes by subsystem; identify public API, schema, and data-flow changes; cover edge cases, failure modes, tests, acceptance criteria, and explicit assumptions. Keep it concise enough to review but detailed enough that another engineer can implement it without making design decisions.

              When ready, call exit_plan_mode with the complete plan markdown, starting with a # title. Make exit_plan_mode the only and final tool call in that assistant response: it presents the plan for approval, and implementation begins only in a later step after approval. Do not paste the final plan as a plain reply or ask "should I proceed?" through prose or ask_user_question. If review rejects it, incorporate the feedback and present again. If the review channel is unavailable or aborted, stay in plan mode and ask the user to switch modes manually; do not proceed with implementation.

# ── compaction ──────────────────────────────────────────────────────────────

# \`compaction-basic\` reads \`toolResultPrune\` through \`ctx.get\`, so the pruner must
# share this realm rather than sit outside it.
#
# \`tokenMeter\` is deliberately NOT in this realm: the meter stays on the HOST
# plane, and the rows here resolve that one instance.
- id: compaction
  name: cordis:group
  group: true
  isolate:
    compaction: true
    toolResultPruner: true
  config:
    - id: compaction-basic
      name: '@deepseek-ai/dsh-compaction-basic'
      config:
        # 模型窗口的 25% 触发压缩：1M 窗口即约 250k tokens（按请求包计，
        # 含系统提示词/工具等固定开销，实际在真实对话约 165k 时触发）。
        thresholdRatio: 0.25
        # 触发后仅保留 32k 近期原文：实测保留过大（如 160k）时压缩一次
        # 回收极少、上下文降不下来；32k 可单次回收约 130k。
        retainTokens: 32768

    - id: command-compact
      name: '@deepseek-ai/dsh-command-compact'

    - id: tool-result-pruner
      name: '@deepseek-ai/dsh-compaction-tool-result-pruner'
      config:
        thresholdChars: 8192
        headChars: 4096
        tailChars: 1024

# ── delegation and workflows ────────────────────────────────────────────────

# The \`subagents\` registry and its spawn/fork backends live in the HOST
# composition; this preset contributes the delegation TOOLS. \`workflows\` rows
# share one entry-local realm because nothing outside an agent reads it.
- id: delegation
  name: cordis:group
  group: true
  isolate:
    workflowEngine: true
  config:
    - id: tool-subagent-control
      name: '@deepseek-ai/dsh-tool-subagent-control'

    - id: tool-subagent-list-agents
      name: '@deepseek-ai/dsh-tool-subagent-control/list-agents'

    - id: tool-subagent
      name: '@deepseek-ai/dsh-tool-subagent'
      config:
        provider: spawn
        toolName: subagent
        modelSelectionSettings: true
        backgroundMode: continuable

    # Fork omits model selection so provider/model stay equal to the parent and
    # the inherited history remains eligible for KV Cache reuse.
    - id: tool-subagent-fork
      name: '@deepseek-ai/dsh-tool-subagent'
      config:
        provider: fork
        toolName: subagent_fork
        backgroundMode: continuable

    # Production dsh does not install these optional providers. Install the
    # matching Bundle in this Profile and restart the Host, then remove
    # \`disabled\` from the matching tool row. Host availability alone grants no tool.
    - id: tool-subagent-codex
      name: '@deepseek-ai/dsh-tool-subagent'
      disabled: true
      config:
        provider: codex
        toolName: subagent_codex
        backgroundMode: one-shot
        maxDepth: provider-managed

    - id: tool-subagent-claude-code
      name: '@deepseek-ai/dsh-tool-subagent'
      disabled: true
      config:
        provider: claude-code
        toolName: subagent_claude_code
        backgroundMode: one-shot
        maxDepth: provider-managed

    - id: workflow-worker-thread
      name: '@deepseek-ai/dsh-workflow-worker-thread'
      config:
        provider: spawn

    - id: tool-workflow
      name: '@deepseek-ai/dsh-tool-workflow'

    - id: tool-ralph
      name: '@deepseek-ai/dsh-tool-ralph'
      config:
        subagentProvider: spawn
        maxRounds: 64

# ── remaining model-facing rows ─────────────────────────────────────────────

- id: tool-ask-user
  name: '@deepseek-ai/dsh-tool-ask-user'

- id: tool-todo
  name: '@deepseek-ai/dsh-tool-todo'
  config:
    allowParallelInProgress: true

# The \`web\` service and its search provider stay in the host composition; only
# the model-facing tool is per-session.
- id: tool-web
  name: '@deepseek-ai/dsh-tool-web'
  config:
    fetch: true
    searchTimeoutMs: 60000

# The skill tool resolves the host/global skill registries; the preset-local
# composition-authoring skill directory is intentionally not bundled here.
- id: tool-skill
  name: '@deepseek-ai/dsh-tool-skill'
`
