/**
 * 天工造梦内置皮肤目录 —— 纯数据层（不含任何 node / DOM 依赖，可由
 * Node 单测与浏览器共用）。
 *
 * 设计原则（与社区换肤插件对齐）：
 *   1. 每套皮肤 = 官方 ThemeDefinition（id + colorScheme + tokens）；
 *   2. tokens 全量覆盖 27 个 --dsw-alias-* / --dsw-specific-* 变量，
 *      替换 DSH Web GUI 的浅色/深色底面，避免依赖宿主默认色造成观感漂移；
 *   3. 深浅两套分开注册为独立主题，由官方 ThemeRuntime 自动同步
 *      body[data-ds-dark-theme]，与 GUI 自带的 light/dark 切换联动；
 *   4. labelKey 走 locale 字典，漏译会在单测里直接报错。
 *
 * 14 套主题覆盖浅色 7 套与深色 7 套，强调点为克制的材质与配色
 * （与社区皮肤插件差异化，色值与命名皆为本仓库原创）。
 */

import type { ThemeDefinition } from '@deepseek-ai/dsh-client-ui-theme/client'
import type { DevforgeKey } from '../locales.ts'
import { THEME_BACKGROUNDS } from './backgrounds.ts'

/** 单套皮肤的全部 token key 列表（测试 + 文档的真相源）。 */
export const REQUIRED_TOKEN_KEYS = [
  '--dsw-alias-bg-base',
  '--dsw-alias-bg-layer-1',
  '--dsw-alias-bg-layer-2',
  '--dsw-alias-bg-layer-3',
  '--dsw-alias-bg-overlay',
  '--dsw-alias-border-l1',
  '--dsw-alias-border-l2',
  '--dsw-alias-label-primary',
  '--dsw-alias-label-secondary',
  '--dsw-alias-label-tertiary',
  '--dsw-alias-brand-primary',
  '--dsw-alias-brand-text',
  '--dsw-alias-button-primary-hover',
  '--dsw-alias-button-primary-dimmed',
  '--dsw-alias-state-business-primary',
  '--dsw-alias-state-business-tertiary',
  '--dsw-alias-interactive-bg-hover',
  '--dsw-alias-interactive-bg-active',
  '--dsw-alias-markdown-code-block',
  '--dsw-alias-markdown-inline-code',
  '--dsw-specific-sidebar-fill',
  '--dsw-specific-sidebar-nav-item-active',
  '--dsw-specific-sidebar-nav-item-hover',
  '--dsw-alias-scrollbar-bg-l1',
  '--dsw-alias-scrollbar-bg-l2',
  '--dsw-alias-scrollbar-hover-l1',
  '--dsw-alias-scrollbar-hover-l2',
] as const

/** 一套主题定义（叠加 labelKey）。 */
export interface SkinDefinition extends ThemeDefinition {
  /** locale key（zh/en 都必填，单测断言）。 */
  labelKey: DevforgeKey
  /** 与主题绑定的默认背景图；用户手动壁纸存在时由运行时让位。 */
  backgroundImage: string
}

/** 内置皮肤目录 —— 注册顺序即 GUI 皮肤选择器的展示顺序。 */
export const SKINS: readonly SkinDefinition[] = [
  {
    id: 'devforge-dawn-mist',
    labelKey: 'skin.dawnMist',
    backgroundImage: THEME_BACKGROUNDS['devforge-dawn-mist'],
    colorScheme: 'light',
    tokens: {
      '--dsw-alias-bg-base': '#f6f9fd',
      '--dsw-alias-bg-layer-1': '#ffffff',
      '--dsw-alias-bg-layer-2': '#ecf2fa',
      '--dsw-alias-bg-layer-3': '#dfe9f6',
      '--dsw-alias-bg-overlay': '#fbfdff',
      '--dsw-alias-border-l1': 'rgba(47, 111, 237, 0.12)',
      '--dsw-alias-border-l2': 'rgba(47, 111, 237, 0.2)',
      '--dsw-alias-label-primary': '#1a2433',
      '--dsw-alias-label-secondary': '#5b6b82',
      '--dsw-alias-label-tertiary': '#8494ab',
      '--dsw-alias-brand-primary': '#2f6fed',
      '--dsw-alias-brand-text': '#ffffff',
      '--dsw-alias-button-primary-hover': '#255cd2',
      '--dsw-alias-button-primary-dimmed': '#e3edfd',
      '--dsw-alias-state-business-primary': '#2f6fed',
      '--dsw-alias-state-business-tertiary': '#e3edfd',
      '--dsw-alias-interactive-bg-hover': 'rgba(47, 111, 237, 0.08)',
      '--dsw-alias-interactive-bg-active': 'rgba(47, 111, 237, 0.14)',
      '--dsw-alias-markdown-code-block': '#ecf2fa',
      '--dsw-alias-markdown-inline-code': '#e0eaf8',
      '--dsw-specific-sidebar-fill': '#ecf2fa',
      '--dsw-specific-sidebar-nav-item-active': '#dfe9f6',
      '--dsw-specific-sidebar-nav-item-hover': '#e6eef8',
      '--dsw-alias-scrollbar-bg-l1': '#d8e2f0',
      '--dsw-alias-scrollbar-bg-l2': '#cdd9ea',
      '--dsw-alias-scrollbar-hover-l1': '#b9c9e0',
      '--dsw-alias-scrollbar-hover-l2': '#b9c9e0',
    },
  },
  {
    id: 'devforge-sakura',
    labelKey: 'skin.sakura',
    backgroundImage: THEME_BACKGROUNDS['devforge-sakura'],
    colorScheme: 'light',
    tokens: {
      '--dsw-alias-bg-base': '#fdf5f8',
      '--dsw-alias-bg-layer-1': '#ffffff',
      '--dsw-alias-bg-layer-2': '#fae9ef',
      '--dsw-alias-bg-layer-3': '#f4dce6',
      '--dsw-alias-bg-overlay': '#fffbfd',
      '--dsw-alias-border-l1': 'rgba(219, 39, 119, 0.12)',
      '--dsw-alias-border-l2': 'rgba(219, 39, 119, 0.2)',
      '--dsw-alias-label-primary': '#33202a',
      '--dsw-alias-label-secondary': '#83606f',
      '--dsw-alias-label-tertiary': '#a58592',
      '--dsw-alias-brand-primary': '#db2777',
      '--dsw-alias-brand-text': '#ffffff',
      '--dsw-alias-button-primary-hover': '#c2206a',
      '--dsw-alias-button-primary-dimmed': '#fae3ec',
      '--dsw-alias-state-business-primary': '#db2777',
      '--dsw-alias-state-business-tertiary': '#fae3ec',
      '--dsw-alias-interactive-bg-hover': 'rgba(219, 39, 119, 0.08)',
      '--dsw-alias-interactive-bg-active': 'rgba(219, 39, 119, 0.14)',
      '--dsw-alias-markdown-code-block': '#fae9ef',
      '--dsw-alias-markdown-inline-code': '#f6dfe8',
      '--dsw-specific-sidebar-fill': '#fae9ef',
      '--dsw-specific-sidebar-nav-item-active': '#f4dce6',
      '--dsw-specific-sidebar-nav-item-hover': '#f7e3eb',
      '--dsw-alias-scrollbar-bg-l1': '#efd2dd',
      '--dsw-alias-scrollbar-bg-l2': '#eac6d4',
      '--dsw-alias-scrollbar-hover-l1': '#ddb0c1',
      '--dsw-alias-scrollbar-hover-l2': '#ddb0c1',
    },
  },
  {
    id: 'devforge-paper',
    labelKey: 'skin.paper',
    backgroundImage: THEME_BACKGROUNDS['devforge-paper'],
    colorScheme: 'light',
    tokens: {
      '--dsw-alias-bg-base': '#faf6ee',
      '--dsw-alias-bg-layer-1': '#fffdf8',
      '--dsw-alias-bg-layer-2': '#f3ecdd',
      '--dsw-alias-bg-layer-3': '#eadfc8',
      '--dsw-alias-bg-overlay': '#fdfaf3',
      '--dsw-alias-border-l1': 'rgba(180, 83, 9, 0.14)',
      '--dsw-alias-border-l2': 'rgba(180, 83, 9, 0.22)',
      '--dsw-alias-label-primary': '#33291a',
      '--dsw-alias-label-secondary': '#7a6c52',
      '--dsw-alias-label-tertiary': '#9c8f77',
      '--dsw-alias-brand-primary': '#b45309',
      '--dsw-alias-brand-text': '#ffffff',
      '--dsw-alias-button-primary-hover': '#9c4708',
      '--dsw-alias-button-primary-dimmed': '#f2e6cf',
      '--dsw-alias-state-business-primary': '#b45309',
      '--dsw-alias-state-business-tertiary': '#f2e6cf',
      '--dsw-alias-interactive-bg-hover': 'rgba(180, 83, 9, 0.09)',
      '--dsw-alias-interactive-bg-active': 'rgba(180, 83, 9, 0.15)',
      '--dsw-alias-markdown-code-block': '#f3ecdd',
      '--dsw-alias-markdown-inline-code': '#eee2ca',
      '--dsw-specific-sidebar-fill': '#f3ecdd',
      '--dsw-specific-sidebar-nav-item-active': '#eadfc8',
      '--dsw-specific-sidebar-nav-item-hover': '#efe6d4',
      '--dsw-alias-scrollbar-bg-l1': '#e2d5b8',
      '--dsw-alias-scrollbar-bg-l2': '#dacbaa',
      '--dsw-alias-scrollbar-hover-l1': '#c9b78e',
      '--dsw-alias-scrollbar-hover-l2': '#c9b78e',
    },
  },
  {
    id: 'devforge-forest',
    labelKey: 'skin.forest',
    backgroundImage: THEME_BACKGROUNDS['devforge-forest'],
    colorScheme: 'light',
    tokens: {
      '--dsw-alias-bg-base': '#f4faf5',
      '--dsw-alias-bg-layer-1': '#ffffff',
      '--dsw-alias-bg-layer-2': '#e8f4ea',
      '--dsw-alias-bg-layer-3': '#d9ecdd',
      '--dsw-alias-bg-overlay': '#f9fdfa',
      '--dsw-alias-border-l1': 'rgba(22, 163, 74, 0.13)',
      '--dsw-alias-border-l2': 'rgba(22, 163, 74, 0.2)',
      '--dsw-alias-label-primary': '#14251a',
      '--dsw-alias-label-secondary': '#5c7263',
      '--dsw-alias-label-tertiary': '#87a08f',
      '--dsw-alias-brand-primary': '#16a34a',
      '--dsw-alias-brand-text': '#ffffff',
      '--dsw-alias-button-primary-hover': '#128a3e',
      '--dsw-alias-button-primary-dimmed': '#dff0e3',
      '--dsw-alias-state-business-primary': '#16a34a',
      '--dsw-alias-state-business-tertiary': '#dff0e3',
      '--dsw-alias-interactive-bg-hover': 'rgba(22, 163, 74, 0.08)',
      '--dsw-alias-interactive-bg-active': 'rgba(22, 163, 74, 0.14)',
      '--dsw-alias-markdown-code-block': '#e8f4ea',
      '--dsw-alias-markdown-inline-code': '#dfeee2',
      '--dsw-specific-sidebar-fill': '#e8f4ea',
      '--dsw-specific-sidebar-nav-item-active': '#d9ecdd',
      '--dsw-specific-sidebar-nav-item-hover': '#e0efe4',
      '--dsw-alias-scrollbar-bg-l1': '#cfe4d4',
      '--dsw-alias-scrollbar-bg-l2': '#c2dcca',
      '--dsw-alias-scrollbar-hover-l1': '#a9cdb2',
      '--dsw-alias-scrollbar-hover-l2': '#a9cdb2',
    },
  },
  {
    id: 'devforge-citrus',
    labelKey: 'skin.citrus',
    backgroundImage: THEME_BACKGROUNDS['devforge-citrus'],
    colorScheme: 'light',
    tokens: {
      '--dsw-alias-bg-base': '#fdf8f2',
      '--dsw-alias-bg-layer-1': '#ffffff',
      '--dsw-alias-bg-layer-2': '#faeede',
      '--dsw-alias-bg-layer-3': '#f5e2c8',
      '--dsw-alias-bg-overlay': '#fffcf7',
      '--dsw-alias-border-l1': 'rgba(234, 88, 12, 0.13)',
      '--dsw-alias-border-l2': 'rgba(234, 88, 12, 0.2)',
      '--dsw-alias-label-primary': '#302214',
      '--dsw-alias-label-secondary': '#7d6a55',
      '--dsw-alias-label-tertiary': '#a4917b',
      '--dsw-alias-brand-primary': '#ea580c',
      '--dsw-alias-brand-text': '#ffffff',
      '--dsw-alias-button-primary-hover': '#d14e0a',
      '--dsw-alias-button-primary-dimmed': '#fbe6d2',
      '--dsw-alias-state-business-primary': '#ea580c',
      '--dsw-alias-state-business-tertiary': '#fbe6d2',
      '--dsw-alias-interactive-bg-hover': 'rgba(234, 88, 12, 0.08)',
      '--dsw-alias-interactive-bg-active': 'rgba(234, 88, 12, 0.15)',
      '--dsw-alias-markdown-code-block': '#faeede',
      '--dsw-alias-markdown-inline-code': '#f7e5cd',
      '--dsw-specific-sidebar-fill': '#faeede',
      '--dsw-specific-sidebar-nav-item-active': '#f5e2c8',
      '--dsw-specific-sidebar-nav-item-hover': '#f7e7d0',
      '--dsw-alias-scrollbar-bg-l1': '#eeddc2',
      '--dsw-alias-scrollbar-bg-l2': '#e6d2b0',
      '--dsw-alias-scrollbar-hover-l1': '#d6bd92',
      '--dsw-alias-scrollbar-hover-l2': '#d6bd92',
    },
  },
  {
    id: 'devforge-midnight',
    labelKey: 'skin.midnight',
    backgroundImage: THEME_BACKGROUNDS['devforge-midnight'],
    colorScheme: 'dark',
    tokens: {
      '--dsw-alias-bg-base': '#0f1420',
      '--dsw-alias-bg-layer-1': '#151c2c',
      '--dsw-alias-bg-layer-2': '#1b2438',
      '--dsw-alias-bg-layer-3': '#222e48',
      '--dsw-alias-bg-overlay': '#131926',
      '--dsw-alias-border-l1': 'rgba(122, 162, 247, 0.14)',
      '--dsw-alias-border-l2': 'rgba(122, 162, 247, 0.24)',
      '--dsw-alias-label-primary': '#e6ecf8',
      '--dsw-alias-label-secondary': '#9fb0cc',
      '--dsw-alias-label-tertiary': '#6e7f9c',
      '--dsw-alias-brand-primary': '#5b93f5',
      '--dsw-alias-brand-text': '#ffffff',
      '--dsw-alias-button-primary-hover': '#76a8f7',
      '--dsw-alias-button-primary-dimmed': '#1d2a44',
      '--dsw-alias-state-business-primary': '#5b93f5',
      '--dsw-alias-state-business-tertiary': '#1d2a44',
      '--dsw-alias-interactive-bg-hover': 'rgba(91, 147, 245, 0.12)',
      '--dsw-alias-interactive-bg-active': 'rgba(91, 147, 245, 0.2)',
      '--dsw-alias-markdown-code-block': '#1b2438',
      '--dsw-alias-markdown-inline-code': '#212c44',
      '--dsw-specific-sidebar-fill': '#131a29',
      '--dsw-specific-sidebar-nav-item-active': '#1d2840',
      '--dsw-specific-sidebar-nav-item-hover': '#182236',
      '--dsw-alias-scrollbar-bg-l1': '#243352',
      '--dsw-alias-scrollbar-bg-l2': '#2c3d60',
      '--dsw-alias-scrollbar-hover-l1': '#3a4f7a',
      '--dsw-alias-scrollbar-hover-l2': '#3a4f7a',
    },
  },
  {
    id: 'devforge-graphite',
    labelKey: 'skin.graphite',
    backgroundImage: THEME_BACKGROUNDS['devforge-graphite'],
    colorScheme: 'dark',
    tokens: {
      '--dsw-alias-bg-base': '#131316',
      '--dsw-alias-bg-layer-1': '#1a1a1f',
      '--dsw-alias-bg-layer-2': '#212127',
      '--dsw-alias-bg-layer-3': '#2a2a32',
      '--dsw-alias-bg-overlay': '#17171b',
      '--dsw-alias-border-l1': 'rgba(255, 255, 255, 0.1)',
      '--dsw-alias-border-l2': 'rgba(255, 255, 255, 0.16)',
      '--dsw-alias-label-primary': '#ecedf2',
      '--dsw-alias-label-secondary': '#a3a3b3',
      '--dsw-alias-label-tertiary': '#6f6f80',
      '--dsw-alias-brand-primary': '#7c8cf8',
      '--dsw-alias-brand-text': '#ffffff',
      '--dsw-alias-button-primary-hover': '#939ffb',
      '--dsw-alias-button-primary-dimmed': '#26263a',
      '--dsw-alias-state-business-primary': '#7c8cf8',
      '--dsw-alias-state-business-tertiary': '#26263a',
      '--dsw-alias-interactive-bg-hover': 'rgba(124, 140, 248, 0.1)',
      '--dsw-alias-interactive-bg-active': 'rgba(124, 140, 248, 0.16)',
      '--dsw-alias-markdown-code-block': '#212127',
      '--dsw-alias-markdown-inline-code': '#282832',
      '--dsw-specific-sidebar-fill': '#17171b',
      '--dsw-specific-sidebar-nav-item-active': '#242430',
      '--dsw-specific-sidebar-nav-item-hover': '#1d1d26',
      '--dsw-alias-scrollbar-bg-l1': '#30303a',
      '--dsw-alias-scrollbar-bg-l2': '#3a3a46',
      '--dsw-alias-scrollbar-hover-l1': '#4a4a5a',
      '--dsw-alias-scrollbar-hover-l2': '#4a4a5a',
    },
  },
  {
    id: 'devforge-violet-night',
    labelKey: 'skin.violetNight',
    backgroundImage: THEME_BACKGROUNDS['devforge-violet-night'],
    colorScheme: 'dark',
    tokens: {
      '--dsw-alias-bg-base': '#1c1230',
      '--dsw-alias-bg-layer-1': '#251a3f',
      '--dsw-alias-bg-layer-2': '#2f2150',
      '--dsw-alias-bg-layer-3': '#3a2a62',
      '--dsw-alias-bg-overlay': '#1f1535',
      '--dsw-alias-border-l1': 'rgba(192, 132, 252, 0.2)',
      '--dsw-alias-border-l2': 'rgba(192, 132, 252, 0.32)',
      '--dsw-alias-label-primary': '#f3edff',
      '--dsw-alias-label-secondary': '#b8a5d6',
      '--dsw-alias-label-tertiary': '#8a78a8',
      '--dsw-alias-brand-primary': '#c084fc',
      '--dsw-alias-brand-text': '#ffffff',
      '--dsw-alias-button-primary-hover': '#d8a2ff',
      '--dsw-alias-button-primary-dimmed': '#2e1f55',
      '--dsw-alias-state-business-primary': '#c084fc',
      '--dsw-alias-state-business-tertiary': '#2e1f55',
      '--dsw-alias-interactive-bg-hover': 'rgba(192, 132, 252, 0.14)',
      '--dsw-alias-interactive-bg-active': 'rgba(192, 132, 252, 0.24)',
      '--dsw-alias-markdown-code-block': '#2f2150',
      '--dsw-alias-markdown-inline-code': '#382763',
      '--dsw-specific-sidebar-fill': '#1f1535',
      '--dsw-specific-sidebar-nav-item-active': '#2c1f4f',
      '--dsw-specific-sidebar-nav-item-hover': '#24193f',
      '--dsw-alias-scrollbar-bg-l1': '#3a2a62',
      '--dsw-alias-scrollbar-bg-l2': '#453275',
      '--dsw-alias-scrollbar-hover-l1': '#5a428f',
      '--dsw-alias-scrollbar-hover-l2': '#5a428f',
    },
  },
  {
    id: 'devforge-pine-night',
    labelKey: 'skin.pineNight',
    backgroundImage: THEME_BACKGROUNDS['devforge-pine-night'],
    colorScheme: 'dark',
    tokens: {
      '--dsw-alias-bg-base': '#0b1411',
      '--dsw-alias-bg-layer-1': '#101c17',
      '--dsw-alias-bg-layer-2': '#152420',
      '--dsw-alias-bg-layer-3': '#1b2e29',
      '--dsw-alias-bg-overlay': '#0d1815',
      '--dsw-alias-border-l1': 'rgba(63, 206, 143, 0.14)',
      '--dsw-alias-border-l2': 'rgba(63, 206, 143, 0.24)',
      '--dsw-alias-label-primary': '#e4f2ea',
      '--dsw-alias-label-secondary': '#96b3a4',
      '--dsw-alias-label-tertiary': '#6c8a7c',
      '--dsw-alias-brand-primary': '#3fce8f',
      '--dsw-alias-brand-text': '#ffffff',
      '--dsw-alias-button-primary-hover': '#5adaa3',
      '--dsw-alias-button-primary-dimmed': '#12271f',
      '--dsw-alias-state-business-primary': '#3fce8f',
      '--dsw-alias-state-business-tertiary': '#12271f',
      '--dsw-alias-interactive-bg-hover': 'rgba(63, 206, 143, 0.1)',
      '--dsw-alias-interactive-bg-active': 'rgba(63, 206, 143, 0.18)',
      '--dsw-alias-markdown-code-block': '#152420',
      '--dsw-alias-markdown-inline-code': '#1a2c26',
      '--dsw-specific-sidebar-fill': '#0e1a15',
      '--dsw-specific-sidebar-nav-item-active': '#16291f',
      '--dsw-specific-sidebar-nav-item-hover': '#122119',
      '--dsw-alias-scrollbar-bg-l1': '#1e322a',
      '--dsw-alias-scrollbar-bg-l2': '#254034',
      '--dsw-alias-scrollbar-hover-l1': '#325547',
      '--dsw-alias-scrollbar-hover-l2': '#325547',
    },
  },
  {
    id: 'devforge-jade-ink',
    labelKey: 'skin.jadeInk',
    backgroundImage: THEME_BACKGROUNDS['devforge-jade-ink'],
    colorScheme: 'dark',
    tokens: {
      '--dsw-alias-bg-base': '#0c1517',
      '--dsw-alias-bg-layer-1': '#111d20',
      '--dsw-alias-bg-layer-2': '#162529',
      '--dsw-alias-bg-layer-3': '#1d3036',
      '--dsw-alias-bg-overlay': '#0e191c',
      '--dsw-alias-border-l1': 'rgba(47, 212, 197, 0.14)',
      '--dsw-alias-border-l2': 'rgba(47, 212, 197, 0.24)',
      '--dsw-alias-label-primary': '#e2f1f0',
      '--dsw-alias-label-secondary': '#93afb0',
      '--dsw-alias-label-tertiary': '#6a8889',
      '--dsw-alias-brand-primary': '#2fd4c5',
      '--dsw-alias-brand-text': '#ffffff',
      '--dsw-alias-button-primary-hover': '#4eddd0',
      '--dsw-alias-button-primary-dimmed': '#0f2a28',
      '--dsw-alias-state-business-primary': '#2fd4c5',
      '--dsw-alias-state-business-tertiary': '#0f2a28',
      '--dsw-alias-interactive-bg-hover': 'rgba(47, 212, 197, 0.1)',
      '--dsw-alias-interactive-bg-active': 'rgba(47, 212, 197, 0.18)',
      '--dsw-alias-markdown-code-block': '#162529',
      '--dsw-alias-markdown-inline-code': '#1a2c30',
      '--dsw-specific-sidebar-fill': '#0f1b1d',
      '--dsw-specific-sidebar-nav-item-active': '#152729',
      '--dsw-specific-sidebar-nav-item-hover': '#122122',
      '--dsw-alias-scrollbar-bg-l1': '#1e3236',
      '--dsw-alias-scrollbar-bg-l2': '#243d42',
      '--dsw-alias-scrollbar-hover-l1': '#2f5057',
      '--dsw-alias-scrollbar-hover-l2': '#2f5057',
    },
  },
  {
    id: 'devforge-lavender',
    labelKey: 'skin.lavender',
    backgroundImage: THEME_BACKGROUNDS['devforge-lavender'],
    colorScheme: 'light',
    tokens: {
      '--dsw-alias-bg-base': '#f6f3fb',
      '--dsw-alias-bg-layer-1': '#ffffff',
      '--dsw-alias-bg-layer-2': '#ece6f6',
      '--dsw-alias-bg-layer-3': '#dfd6ef',
      '--dsw-alias-bg-overlay': '#fbf8fe',
      '--dsw-alias-border-l1': 'rgba(139, 92, 246, 0.14)',
      '--dsw-alias-border-l2': 'rgba(139, 92, 246, 0.22)',
      '--dsw-alias-label-primary': '#221634',
      '--dsw-alias-label-secondary': '#6a5d80',
      '--dsw-alias-label-tertiary': '#9489a8',
      '--dsw-alias-brand-primary': '#8b5cf6',
      '--dsw-alias-brand-text': '#ffffff',
      '--dsw-alias-button-primary-hover': '#7c4ce0',
      '--dsw-alias-button-primary-dimmed': '#ece6f6',
      '--dsw-alias-state-business-primary': '#8b5cf6',
      '--dsw-alias-state-business-tertiary': '#ece6f6',
      '--dsw-alias-interactive-bg-hover': 'rgba(139, 92, 246, 0.08)',
      '--dsw-alias-interactive-bg-active': 'rgba(139, 92, 246, 0.14)',
      '--dsw-alias-markdown-code-block': '#ece6f6',
      '--dsw-alias-markdown-inline-code': '#e2daf1',
      '--dsw-specific-sidebar-fill': '#ece6f6',
      '--dsw-specific-sidebar-nav-item-active': '#dfd6ef',
      '--dsw-specific-sidebar-nav-item-hover': '#e6def2',
      '--dsw-alias-scrollbar-bg-l1': '#d8cde8',
      '--dsw-alias-scrollbar-bg-l2': '#cbc0e0',
      '--dsw-alias-scrollbar-hover-l1': '#b5a7d2',
      '--dsw-alias-scrollbar-hover-l2': '#b5a7d2',
    },
  },
  {
    id: 'devforge-wisteria',
    labelKey: 'skin.wisteria',
    backgroundImage: THEME_BACKGROUNDS['devforge-wisteria'],
    colorScheme: 'light',
    tokens: {
      '--dsw-alias-bg-base': '#faf5fd',
      '--dsw-alias-bg-layer-1': '#ffffff',
      '--dsw-alias-bg-layer-2': '#f1e5f8',
      '--dsw-alias-bg-layer-3': '#e7d3f2',
      '--dsw-alias-bg-overlay': '#fefcff',
      '--dsw-alias-border-l1': 'rgba(168, 85, 247, 0.14)',
      '--dsw-alias-border-l2': 'rgba(168, 85, 247, 0.22)',
      '--dsw-alias-label-primary': '#2a1a3a',
      '--dsw-alias-label-secondary': '#735a85',
      '--dsw-alias-label-tertiary': '#9d86af',
      '--dsw-alias-brand-primary': '#a855f7',
      '--dsw-alias-brand-text': '#ffffff',
      '--dsw-alias-button-primary-hover': '#9333ea',
      '--dsw-alias-button-primary-dimmed': '#f1e5f8',
      '--dsw-alias-state-business-primary': '#a855f7',
      '--dsw-alias-state-business-tertiary': '#f1e5f8',
      '--dsw-alias-interactive-bg-hover': 'rgba(168, 85, 247, 0.08)',
      '--dsw-alias-interactive-bg-active': 'rgba(168, 85, 247, 0.14)',
      '--dsw-alias-markdown-code-block': '#f1e5f8',
      '--dsw-alias-markdown-inline-code': '#e9dbf3',
      '--dsw-specific-sidebar-fill': '#f1e5f8',
      '--dsw-specific-sidebar-nav-item-active': '#e7d3f2',
      '--dsw-specific-sidebar-nav-item-hover': '#ecdded',
      '--dsw-alias-scrollbar-bg-l1': '#dfcaea',
      '--dsw-alias-scrollbar-bg-l2': '#d4bce2',
      '--dsw-alias-scrollbar-hover-l1': '#bf9fd2',
      '--dsw-alias-scrollbar-hover-l2': '#bf9fd2',
    },
  },
  {
    id: 'devforge-crystal-violet',
    labelKey: 'skin.crystalViolet',
    backgroundImage: THEME_BACKGROUNDS['devforge-crystal-violet'],
    colorScheme: 'dark',
    tokens: {
      '--dsw-alias-bg-base': '#14101e',
      '--dsw-alias-bg-layer-1': '#1a1528',
      '--dsw-alias-bg-layer-2': '#231b36',
      '--dsw-alias-bg-layer-3': '#2d2346',
      '--dsw-alias-bg-overlay': '#181224',
      '--dsw-alias-border-l1': 'rgba(196, 181, 253, 0.18)',
      '--dsw-alias-border-l2': 'rgba(196, 181, 253, 0.28)',
      '--dsw-alias-label-primary': '#ede4ff',
      '--dsw-alias-label-secondary': '#a89cc8',
      '--dsw-alias-label-tertiary': '#7e729a',
      '--dsw-alias-brand-primary': '#c4b5fd',
      '--dsw-alias-brand-text': '#ffffff',
      '--dsw-alias-button-primary-hover': '#d6caff',
      '--dsw-alias-button-primary-dimmed': '#241a3d',
      '--dsw-alias-state-business-primary': '#c4b5fd',
      '--dsw-alias-state-business-tertiary': '#241a3d',
      '--dsw-alias-interactive-bg-hover': 'rgba(196, 181, 253, 0.12)',
      '--dsw-alias-interactive-bg-active': 'rgba(196, 181, 253, 0.2)',
      '--dsw-alias-markdown-code-block': '#231b36',
      '--dsw-alias-markdown-inline-code': '#2a2143',
      '--dsw-specific-sidebar-fill': '#181224',
      '--dsw-specific-sidebar-nav-item-active': '#262041',
      '--dsw-specific-sidebar-nav-item-hover': '#1f1933',
      '--dsw-alias-scrollbar-bg-l1': '#2d2346',
      '--dsw-alias-scrollbar-bg-l2': '#382b58',
      '--dsw-alias-scrollbar-hover-l1': '#4a3a72',
      '--dsw-alias-scrollbar-hover-l2': '#4a3a72',
    },
  },
  {
    // 中国红（深色 v2）：红墙暗面深绛底 + 朱砂 #e34234 主色 + 宣纸白文字。
    // v1 的浅色朱染被辉哥反馈「像粉色」——红色大面积稀释必然发粉，
    // 改为深色红墙底，主色用高饱和朱砂，一眼即是中国红。
    id: 'devforge-china-red',
    labelKey: 'skin.chinaRed',
    backgroundImage: THEME_BACKGROUNDS['devforge-china-red'],
    colorScheme: 'dark',
    tokens: {
      '--dsw-alias-bg-base': '#260b0f',
      '--dsw-alias-bg-layer-1': '#301015',
      '--dsw-alias-bg-layer-2': '#3c141a',
      '--dsw-alias-bg-layer-3': '#4a181f',
      '--dsw-alias-bg-overlay': '#2a0d12',
      '--dsw-alias-border-l1': 'rgba(255, 138, 130, 0.15)',
      '--dsw-alias-border-l2': 'rgba(255, 138, 130, 0.24)',
      '--dsw-alias-label-primary': '#f9ecdf',
      '--dsw-alias-label-secondary': '#d6a294',
      '--dsw-alias-label-tertiary': '#a5766c',
      '--dsw-alias-brand-primary': '#e34234',
      '--dsw-alias-brand-text': '#ffffff',
      '--dsw-alias-button-primary-hover': '#ee5a4d',
      '--dsw-alias-button-primary-dimmed': '#3f1712',
      '--dsw-alias-state-business-primary': '#e34234',
      '--dsw-alias-state-business-tertiary': '#3f1712',
      '--dsw-alias-interactive-bg-hover': 'rgba(227, 66, 52, 0.13)',
      '--dsw-alias-interactive-bg-active': 'rgba(227, 66, 52, 0.2)',
      '--dsw-alias-markdown-code-block': '#3c141a',
      '--dsw-alias-markdown-inline-code': '#451922',
      '--dsw-specific-sidebar-fill': '#2b0e12',
      '--dsw-specific-sidebar-nav-item-active': '#3c141a',
      '--dsw-specific-sidebar-nav-item-hover': '#331116',
      '--dsw-alias-scrollbar-bg-l1': '#4a181f',
      '--dsw-alias-scrollbar-bg-l2': '#571e26',
      '--dsw-alias-scrollbar-hover-l1': '#6e2a32',
      '--dsw-alias-scrollbar-hover-l2': '#6e2a32',
    },
  },
]

/** 快速按 id 查找（运行时皮肤切换校验用）。 */
export function findSkin(id: string): SkinDefinition | undefined {
  return SKINS.find((s) => s.id === id)
}
